version: '3.8'

services:
  redis-news-cache:
    image: redis:latest
    container_name: redis-news-cache
    ports:
      - "6000:6379"
    networks:
      - internal-network

  redis-api-cache:
    image: redis:latest
    container_name: redis-api-cache
    ports:
      - "5000:6379"
    networks:
      - internal-network

  feed-api:
    build:
      context: .
      dockerfile: Dockerfile.feed-api
    container_name: feed-api
    env_file:
      - ./docker-internals/api-cache.env
    depends_on:
      - redis-news-cache
      - redis-api-cache
    expose:
      - "8080"
    networks:
      - internal-network

  feed-curator:
    build:
      context: .
      dockerfile: Dockerfile.feed-curator
    container_name: feed-curator
    env_file:
      - ./docker-internals/news-cache.env
    depends_on:
      - redis-news-cache
    networks:
      - internal-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker-internals/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - feed-api
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
