name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images to GHCR
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker CLI
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push feed-api image
    - name: Build and push feed-api image
      run: |
        docker build -f Dockerfile.feed-api -t ghcr.io/stockic/stockic-feed-api:latest .
        docker push ghcr.io/stockic/stockic-feed-api:latest

    # Build and push feed-curator image
    - name: Build and push feed-curator image
      run: |
        docker build -f Dockerfile.feed-curator -t ghcr.io/stockic/stockic-curator-api:latest .
        docker push ghcr.io/stockic/stockic-curator-api:latest
