name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images to DigitalOcean
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'

    - name: Install doctl
      run: |
        curl -sL https://github.com/digitalocean/doctl/releases/latest/download/doctl-linux-amd64.tar.gz | tar -xz
        sudo mv doctl /usr/local/bin/

    - name: Authenticate with DigitalOcean
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DOCR_ACCESS_TOKEN }}
      run: |
        doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN
        doctl registry login

    - name: Run make
      run: make 

    - name: Run make clean
      run: make clean

    - name: Build Success
      if: success()
      run: echo "Build completed successfully with make."

    - name: Success Notification
      if: success()
      run: echo "Go binary compiled successfully ... Moving forward to create Docker Images"

    - name: Build and push feed-api image
      run: |
        docker buildx build --platform linux/amd64 -f Dockerfile.feed-api -t registry.digitalocean.com/your-registry-name/feed-api:latest .
        docker push registry.digitalocean.com/your-registry-name/feed-api:latest

    - name: Build and push feed-curator image
      run: |
        docker buildx build --platform linux/amd64 -f Dockerfile.feed-curator -t registry.digitalocean.com/your-registry-name/feed-curator:latest .
        docker push registry.digitalocean.com/your-registry-name/feed-curator:latest
